USE [CDS_OP]
GO

/****** Object:  Table [dbo].[extract]    Script Date: 05/07/2017 15:26:06 ******/
DROP TABLE [dbo].[extract]
GO

/****** Object:  Table [dbo].[extract]    Script Date: 05/07/2017 15:26:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[extract](
[Import_id][int]NOT NULL
,[MostRecent_Flag][bit]
,[CDSMessageType][varchar](6)NULL
,[CDSMessageVersionNumber][varchar](8)NULL
,[CDSMessageReference][int]NULL
,[CDSRecordIdentifier][varchar](35)NULL
,[CDSTypeCode][smallint]NULL
,[CDSProtocolIdentifierCode][smallint]NULL
,[CDSUniqueIdentifier][varchar](35)NULL
,[CDSBulkReplacementGroupCode][smallint]NULL
,[CDSExtractDate][date]NULL
,[CDSExtractTime][time]NULL
,[CDSReportPeriodStartDate][date]NULL
,[CDSReportPeriodEndDate][date]NULL
,[CDSActivityDate][date]NULL
,[OrganisationCode_CDSSenderIdentity][varchar](5)NULL
,[OrganisationCode_CDSPrimeRecipientIdentity][varchar](5)NULL
,[OrganisationCode_CDSCopyRecipientIdentity_1][varchar](5)NULL
,[OrganisationCode_CDSCopyRecipientIdentity_2][varchar](5)NULL
,[OrganisationCode_CDSCopyRecipientIdentity_3][varchar](5)NULL
,[OrganisationCode_CDSCopyRecipientIdentity_4][varchar](5)NULL
,[OrganisationCode_CDSCopyRecipientIdentity_5][varchar](5)NULL
,[OrganisationCode_CDSCopyRecipientIdentity_6][varchar](5)NULL
,[OrganisationCode_CDSCopyRecipientIdentity_7][varchar](5)NULL
,[UniqueBookingReferenceNumber_Converted][int]NULL
,[PatientPathwayIdentifier][varchar](20)NULL
,[OrganisationCode_PatientPathwayIdentifierIssuer][varchar](6)NULL
,[ReferralToTreatmentPeriod_Status][smallint]NULL
,[WaitingTimeMeasurementType][smallint]NULL
,[ReferralToTreatmentPeriod_StartDate][date]NULL
,[ReferralToTreatmentPeriod_EndDate][date]NULL
,[LocalPatientIdentifier][int]NULL
,[OrganisationCode_LocalPatientIdentifier][varchar](5)NULL
,[NHSNumber][bigint]NULL
,[NHSNumberStatusIndicatorCode][smallint]NULL
,[PersonFullName][varchar](70)NULL
,[PersonTitle][varchar](35)NULL
,[PersonGivenName][varchar](35)NULL
,[PersonFamilyName][varchar](35)NULL
,[PersonNameSuffix][varchar](35)NULL
,[PersonInititials][varchar](35)NULL
,[PersonRequestedName][varchar](70)NULL
,[UnstructuredAddress][varchar](175)NULL
,[StructuredAddressLine_1][varchar](35)NULL
,[StructuredAddressLine_2][varchar](35)NULL
,[StructuredAddressLine_3][varchar](35)NULL
,[StructuredAddressLine_4][varchar](35)NULL
,[StructuredAddressLine_5][varchar](35)NULL
,[PostcodeOfUsualAddress][varchar](8)NULL
,[OrganisationCode_ResidenceResponsibility][varchar](3)NULL
,[WithheldIdentityReason][varchar](2)NULL
,[PersonBirthDate][date]NULL
,[PersonGenderCodeCurrent][smallint]NULL
,[CarerSupportIndicator][smallint]NULL
,[EthnicCategory][varchar](2)NULL
,[ConsultantCode][varchar](8)NULL
,[CareProfessionalMainSpecialtyCode][smallint]NULL
,[ActivityTreatmentFunctionCode][smallint]NULL
,[LocalSubSpecialtyCode][int]NULL
,[DiagnosisSchemeInUse][varchar](2)NULL
,[PrimaryDiagnosis_ICD][varchar](6)NULL
,[PresentOnAdmissionIndicator_ICD][varchar](1)NULL
,[SecondaryDiagnosis_ICD_1][varchar](6)NULL
,[PresentOnAdmissionIndicator_ICD_1][varchar](1)NULL
,[SecondaryDiagnosis_ICD_2][varchar](6)NULL
,[PresentOnAdmissionIndicator_ICD_2][varchar](1)NULL
,[SecondaryDiagnosis_ICD_3][varchar](6)NULL
,[PresentOnAdmissionIndicator_ICD_3][smallint]NULL
,[SecondaryDiagnosis_ICD_4][int]NULL
,[PresentOnAdmissionIndicator_ICD_4][smallint]NULL
,[SecondaryDiagnosis_ICD_5][int]NULL
,[PresentOnAdmissionIndicator_ICD_5][smallint]NULL
,[SecondaryDiagnosis_ICD_6][int]NULL
,[PresentOnAdmissionIndicator_ICD_6][varchar](10)NULL
,[SecondaryDiagnosis_ICD_7][varchar](6)NULL
,[PresentOnAdmissionIndicator_ICD_7][smallint]NULL
,[SecondaryDiagnosis_ICD_8][varchar](6)NULL
,[PresentOnAdmissionIndicator_ICD_8][varchar](1)NULL
,[SecondaryDiagnosis_ICD_9][int]NULL
,[PresentOnAdmissionIndicator_ICD_9][smallint]NULL
,[SecondaryDiagnosis_ICD_10][varchar](6)NULL
,[PresentOnAdmissionIndicator_ICD_10][varchar](1)NULL
,[SecondaryDiagnosis_ICD_11][varchar](6)NULL
,[PresentOnAdmissionIndicator_ICD_11][varchar](1)NULL
,[SecondaryDiagnosis_ICD_12][int]NULL
,[PresentOnAdmissionIndicator_ICD_12][smallint]NULL
,[SecondaryDiagnosis_ICD_13][int]NULL
,[PresentOnAdmissionIndicator_ICD_13][smallint]NULL
,[DiagnosisSchemeInUseRead][smallint]NULL
,[PrimaryDiagnosis_READ][int]NULL
,[SecondaryDiagnosis_READ_1][varchar](7)NULL
,[SecondaryDiagnosis_READ_2][varchar](7)NULL
,[SecondaryDiagnosis_READ_3][varchar](7)NULL
,[SecondaryDiagnosis_READ_4][varchar](7)NULL
,[SecondaryDiagnosis_READ_5][int]NULL
,[SecondaryDiagnosis_READ_6][varchar](7)NULL
,[SecondaryDiagnosis_READ_7][varchar](7)NULL
,[SecondaryDiagnosis_READ_8][varchar](7)NULL
,[SecondaryDiagnosis_READ_9][varchar](7)NULL
,[SecondaryDiagnosis_READ_10][varchar](7)NULL
,[SecondaryDiagnosis_READ_11][varchar](7)NULL
,[SecondaryDiagnosis_READ_12][varchar](7)NULL
,[SecondaryDiagnosis_READ_13][varchar](7)NULL
,[AttendanceIdentifier][varchar](12)NULL
,[AdministrativeCategoryCode][int]NULL
,[AttendanceStatus][int]NULL
,[FirstAttendanceCode][smallint]NULL
,[MedicalStaffTypeSeeingPatient][varchar](2)NULL
,[OperationStatusCode][varchar](1)NULL
,[OutcomeOfAttendanceCode][varchar](1)NULL
,[AppointmentDate][Date]NULL
,[AppointmentTime][Time]NULL
,[ExpectedDurationOfAppointment][int]NULL
,[AgeAtCDSActivityDate][int]NULL
,[OverseasVisitorStatusClassificationAtCDSActivityDate][varchar](1)NULL
,[EarliestReasonableOfferDate][varchar](10)NULL
,[EarliestClinicallyAppropriateDate][varchar](10)NULL
,[ConsultationMediumUsed][varchar](2)NULL
,[MultiProfOrDiscIndCode][varchar](1)NULL
,[RehabilitationAssessmentTeamType][varchar](1)NULL
,[CommissioningSerialNumber][varchar](6)NULL
,[NHSServiceAgreementLineNumber][varchar](10)NULL
,[ProviderReferenceNumber][varchar](17)NULL
,[CommissionerReferenceNumber][varchar](17)NULL
,[OrganisationCode_CodeOfProvider][varchar](5)NULL
,[OrganisationCode_CodeOfCommissioner][varchar](5)NULL
,[ProcedureSchemeInUse_OPCS][varchar](2)NULL
,[PrimaryProcedure_OPCS][varchar](4)NULL
,[PrimaryProcedureDate_OPCS][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCSa][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd/Anaes)_OPCS][varchar](12)NULL
,[Procedure_OPCS_1][varchar](4)NULL
,[ProcedureDate_OPCS_1][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_1_hc][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_1][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_1_as][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_1][varchar](12)NULL
,[Procedure_OPCS_2][varchar](4)NULL
,[ProcedureDate_OPCS_2][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_2][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_2][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_2a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_2][varchar](12)NULL
,[Procedure_OPCS_3][varchar](4)NULL
,[ProcedureDate_OPCS_3][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_3][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_3][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_3a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_3][varchar](12)NULL
,[Procedure_OPCS_4][varchar](4)NULL
,[ProcedureDate_OPCS_4][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_4][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_4][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_4a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_5][varchar](12)NULL
,[Procedure_OPCS_5][varchar](4)NULL
,[ProcedureDate_OPCS_5][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_5][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_5][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_5a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_5a][varchar](12)NULL
,[Procedure_OPCS_6][varchar](4)NULL
,[ProcedureDate_OPCS_6][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_6][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_6][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_6a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_6][varchar](12)NULL
,[Procedure_OPCS_7][varchar](4)NULL
,[ProcedureDate_OPCS_7][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_7][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_7][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_7a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_7][varchar](12)NULL
,[Procedure_OPCS_8][varchar](4)NULL
,[ProcedureDate_OPCS_8][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_8][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_8][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_8a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_8][varchar](12)NULL
,[Procedure_OPCS_9][varchar](4)NULL
,[ProcedureDate_OPCS_9][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_9][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_9][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_9a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_9][varchar](12)NULL
,[Procedure_OPCS_10][varchar](4)NULL
,[ProcedureDate_OPCS_10][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_10][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_10][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_10a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_10][varchar](12)NULL
,[Procedure_OPCS_11][varchar](4)NULL
,[ProcedureDate_OPCS_11][varchar](10)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_11][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier_OPCS_11][varchar](12)NULL
,[ProfessionalRegistrationIssuerCode_OPCS_11a][varchar](2)NULL
,[ProfessionalRegistrationEntryIdentifier(2nd)/Anaes_OPCS_11][varchar](12)NULL
,[ProcedureSchemeInUse_READ][varchar](2)NULL
,[PrimaryProcedure_READ][varchar](7)NULL
,[PrimaryProcedureDate_READ][varchar](10)NULL
,[Procedure_READ_1][varchar](7)NULL
,[ProcedureDate_READ_1][varchar](10)NULL
,[Procedure_READ_2][varchar](7)NULL
,[ProcedureDate_READ_2][varchar](10)NULL
,[Procedure_READ_3][varchar](7)NULL
,[ProcedureDate_READ_3][varchar](10)NULL
,[Procedure_READ_4][varchar](7)NULL
,[ProcedureDate_READ_4][varchar](10)NULL
,[Procedure_READ_5][varchar](7)NULL
,[ProcedureDate_READ_5][varchar](10)NULL
,[Procedure_READ_6][varchar](7)NULL
,[ProcedureDate_READ_6][varchar](10)NULL
,[Procedure_READ_7][varchar](7)NULL
,[ProcedureDate_READ_7][varchar](10)NULL
,[Procedure_READ_8][varchar](7)NULL
,[ProcedureDate_READ_8][varchar](10)NULL
,[Procedure_READ_9][varchar](7)NULL
,[ProcedureDate_READ_9][varchar](10)NULL
,[Procedure_READ_10][varchar](7)NULL
,[ProcedureDate_READ_10][varchar](10)NULL
,[Procedure_READ_11][varchar](7)NULL
,[ProcedureDate_READ_11][varchar](10)NULL
,[LocationClass][varchar](2)NULL
,[SiteCodeOfTreatment][varchar](9)NULL
,[ActivityLocationTypeCode][varchar](3)NULL
,[ClinicCode][varchar](12)NULL
,[GeneralMedicalPractitioner_Specified][varchar](8)NULL
,[GeneralPractice_PatientRegistration][varchar](6)NULL
,[PriorityTypeCode][varchar](1)NULL
,[ServiceTypeRequestedCode][varchar](1)NULL
,[SourceOfReferralForOut_Patients][varchar](2)NULL
,[ReferralRequestReceivedDate][varchar](10)NULL
,[DirectAccessReferralIndicator][varchar](1)NULL
,[ReferrerCode][varchar](8)NULL
,[ReferringOrganisationCode][varchar](6)NULL
,[LastDNAOrPatientCancelledDate][varchar](10)NULL
,[SecondaryDiagnosis_ICD_count][int]NULL
,[SecondaryDiagnosis_ICD][varchar](6)NULL
,[SecondaryDiagnosis_READ_count][int]NULL
,[SecondaryDiagnosis_READ][varchar](7)NULL
,[Procedure_OPCS_count][int]NULL
,[Procedure_OPCS][varchar](14)NULL
,[Procedure_READ_count][int]NULL
,[Procedure_READ][varchar](17)NULL
,[CDSMessageReference_a][varchar](14)NULL

) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


